version: "3.8"

services:
  postgres-core-dev:
    image: postgres:16-alpine
    container_name: shorturl-postgres-core-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password
      POSTGRES_DB: shorturl_core_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_core_dev_data:/var/lib/postgresql/data

volumes:
  postgres_core_dev_data:
